apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
commonLabels:
  environment: uat 
bases:
- ../../../base/polypress

patchesStrategicMerge:
- polypress.yaml

images:
- name: public.ecr.aws/ideacrew/polypress
  newName: public.ecr.aws/ideacrew/polypress
  newTag: me-uat
